name: whatsup
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.13.3
  cloud_functions: 0.4.1+6
  firebase_storage: 3.1.1
  firebase_auth: 0.15.3
  bloc_provider:
  shared_preferences: ^0.5.3+4
  rxdart: ^0.23.1
  cached_network_image: ^2.0.0
  flutter_swiper: ^1.1.6
  flare_flutter:
  giphy_client: ^0.2.0
  flutter_datetime_picker: ^1.3.1
  firebase_remote_config: 0.3.0+3
  image_cropper: ^1.2.1
  image_editor: ^0.1.2
  isolate: ^2.0.2
  flutter_gifimage: ^1.0.0
  extended_image_library: ^0.2.0
  flutter_colorpicker: 0.2.3
  extended_image:
    git:
      url: https://github.com/bubupro9x/extentded_image.git
  image_picker:
  intl: ^0.16.1
  video_player: ^0.10.8+1
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.17.1
  share: ^0.6.3+6
  google_sign_in: ^4.1.4
  flutter_facebook_login: ^3.0.0
  path_provider: ^1.6.5
  flutter_cache_manager: ^1.1.3
  http: ^0.12.0+4
  path: ^1.6.4
  auto_size_text: ^2.1.0
  esys_flutter_share: ^1.0.2
  flutter_ffmpeg:
    git:
      url: https://github.com/tanersener/flutter-ffmpeg.git
  gif_ani: ^0.0.2
  dio: 3.0.9
  photo:
    #path: ../photo
    git:
      url: https://github.com/bubupro9x/photo.git
  sliding_up_panel: ^1.0.1
  image_gallery_saver: ^1.2.2
dependency_overrides:
  firebase_core: 0.4.4
  image: ^2.1.12

  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1 # Analysis


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: AvenirLTStd
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf
        - asset: assets/fonts/AvenirLTStd-Book.otf
          weight: 700
        - asset: assets/fonts/AvenirLTStd-Medium.otf
          weight: 500