import '../models/posts.dart';

List<Posts> posts = [
  Posts('assets/images/1.jpg', 1, 1),
  Posts('assets/images/2.jpg', 2, 1),
  Posts('assets/images/1.jpg', 1, 2),
  Posts('assets/images/cover.jpg', 3, 4),
  Posts('assets/images/2.jpg', 1, 1),
  Posts('assets/images/1.jpg', 4, 2),
  Posts('assets/images/1.jpg', 2, 1),
  Posts('assets/images/2.jpg', 5, 7),
  Posts('assets/images/1.jpg', 19, 8),
  Posts('assets/images/1.jpg', 1, 1),
  Posts('assets/images/2.jpg', 2, 1),
  Posts('assets/images/1.jpg', 1, 2),
  Posts('assets/images/2.jpg', 3, 4),
  Posts('assets/images/2.jpg', 1, 1),
  Posts('assets/images/1.jpg', 4, 2),
  Posts('assets/images/cover.jpg', 2, 1),
  Posts('assets/images/2.jpg', 5, 7),
  Posts('assets/images/1.jpg', 19, 8),
  Posts('assets/images/1.jpg', 1, 1),
  Posts('assets/images/2.jpg', 2, 1),
  Posts('assets/images/1.jpg', 1, 2),
  Posts('assets/images/2.jpg', 3, 4),
  Posts('assets/images/2.jpg', 1, 1),
  Posts('assets/images/cover.jpg', 4, 2),
  Posts('assets/images/1.jpg', 2, 1),
  Posts('assets/images/2.jpg', 5, 7),
  Posts('assets/images/1.jpg', 19, 8),
];
